services:
  api_node_01:
    build: .
    env_file:
      - ./infrastructure/docker.env
    ports:
      - 80:80
    depends_on:
      mongo_db_node_01:
        condition: service_started

  mongo_db_node_01:
    image: mongo:7.0.2
    healthcheck:
      test: echo 'db.RunCommand("ping").ok' | mongosh mongo_db_node_01:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./data/mongo_node_01:/data/db
    command: mongod -replSet docker-replicaset
    ports:
      - 27018:27017

  mongo_cluster_init:
    image: mongo:7.0.2
    depends_on:
      mongo_db_node_01:
        condition: service_healthy
    volumes:
        - ./infrastructure/init_mongo.js:/scripts/init_mongo.js:ro
    entrypoint: ["mongosh", "--host", "mongo_db_node_01", "--file", "/scripts/init_mongo.js"]